### ISSUE TITLE
Request for new PSPP version of AppImage

### ISSUE THREAD

**Issue by vagabondsajib** [fusion809/AppImages#10]
The AppImage File in [this](https://bintray.com/probono/AppImages/GNU_PSPP#files) is very old. Can you please update it to latest package.

**Comment by fusion809** [comment]
This repo hasn't been maintained since 2017. Ideally, you should ask the upstream devs to do this. The whole point of probonopd's repo is to give users and devs alike a taste or sample of what AppImages for major apps would look like and how they might be built, but if you want them nice and up to date you should get the upstream devs to maintain them. If they refuse, there's nothing to stop you from cloning AppImage/AppImages and working on updating the PSPP yaml file yourself. He does have other files there that can serve as examples of how you might do this. 

I'm sorry, mate, but I do have things to do in my life and updating PSPP is likely to take me hours, that's if I can even manage it (I'm nowhere near as skilled at it as probonopd).
